[package]
name = "ctap-hid-fido2"
version = "3.5.9"
authors = ["gebo <35388172+gebogebogebo@users.noreply.github.com>"]
edition = "2021"
rust-version = "1.85"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license="MIT"
description="Rust FIDO2 CTAP library"
repository="https://github.com/gebogebogebo/ctap-hid-fido2"
keywords=["FIDO2","CTAP","CTAP2"]
readme="README.md"

[features]
default = ["ring"]
ring = ["dep:ring"]
aws-lc-rs = ["dep:aws-lc-rs"]
fips = ["aws-lc-rs", "aws-lc-rs/fips"]

[dependencies]
aes = "0.9.0"
anyhow = "1.0.102"
aws-lc-rs = { version = "1.16.3", optional = true }
base64 = "0.22.1"
byteorder = "1.5.0"
cbc = "0.2.0"
hex = "0.4.3"
num = "0.4.3"
pad = "0.1.6"
ring = { version = "0.17.14", optional = true }
ciborium = "0.2.2"
strum = "0.28.0"
strum_macros = "0.28.0"
x509-parser = "0.18.1"


[dependencies.hidapi]
version = "2.6.5"
default-features = false
features=["linux-static-hidraw"]

[dev-dependencies]
clap = { version = "4.6.1", features = ["derive"] }
env_logger = "0.11.10"
log = "0.4.29"
rpassword = "7.5.2"
arboard = "3.6.1"
colored = "3.1.1"

[[example]]
name = "ctapcli"

[[example]]
name = "get-info"

[[example]]
name = "reg-auth"

[[example]]
name = "test-with-pin-non-rk"

[[example]]
name = "test-with-pin-rk"

[[example]]
name = "wink"

[[example]]
name = "test-config"

[[example]]
name = "selection"
