name: macOS + Ubuntu + Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  macos-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --examples --verbose
    - name: Build async
      run: cargo build --examples --features tokio --verbose

  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y libusb-1.0-0-dev libudev-dev
    - name: Build
      run: cargo build --examples --verbose
    - name: Build async
      run: cargo build --examples --features tokio --verbose

  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --examples --verbose
    - name: Build async
      run: cargo build --examples --features tokio --verbose
